CREATE TABLE Scholarship (
   
    Gender TEXT,
    Family_income INTEGER,
    Competitive_Exam TEXT,
    Domicile TEXT, 
    Category TEXT,
    Categories TEXT,
    Score_12th INTEGER,
    AGE INTEGER,
    photo_url TEXT,
    Details TEXT,
    Photo_URL TEXT,

);

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('female' , 300000, 'JEE' , 'Madhya PRADESH' , 'SC/ST', 'National' , 75 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('female' , 500000, 'JEE' , 'Madhya PRADESH' , 'OBC', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('female' , 300000, 'NEET' , 'Madhya PRADESH' , 'SC/ST', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('female' , 500000, 'NEET' , 'Madhya PRADESH' , 'GENERAL', 'National' , 85, 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('female' , 500000, 'JEE' , 'Madhya PRADESH' , 'SC/ST', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('male' , 600000, 'NEET' , 'Madhya PRADESH' , 'SC/ST', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('male' , 600000, 'NEET' , 'Madhya PRADESH' , 'SC/ST', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('male' , 600000, 'NEET' , 'Madhya PRADESH' , 'SC/ST', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('male' , 600000, 'JEE' , 'Madhya PRADESH' , 'SC/ST', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('male' , 600000, 'JEE' , 'Madhya PRADESH' , 'SC/ST', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');



INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('male' , 500000, 'JEE' , 'Madhya PRADESH' , 'SC/ST', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('male' , 500000, 'JEE' , 'Madhya PRADESH' , 'SC/ST', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('male' , 500000, 'NEET' , 'Madhya PRADESH' , 'SC/ST', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('female' , 500000, 'NEET' , 'Madhya PRADESH' , 'SC/ST', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');

INSERT INTO Scholarship (Gender ,Family_income ,Competitive_Exam,Domicile ,Category,Categories ,Score_12th ,AGE ,Details ,Photo_URL ) VALUES ('female' , 500000, 'JEE' , 'Madhya PRADESH' , 'SC/ST', 'National' , 85 , 20 , 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '/public/scholarship_image');


-- Down
DROP TABLE Scholarship;

